Check cluster health before trying to run tests (#1052)
Trying to run tests with an unhealthy cluster may lead to obscure failures like #856.
Explicitly check the status of the cluster before running tests, and report the underlying
cause of the problem.

For example, when running tests with low disk, execution is aborted with this error
obtained from Elasticsearch internal health endpoint:

```
Error: cluster in unhealthy state: 33 indices reside on nodes that have run or are likelyto run out of disk space, this can temporarily disable writing on these indices.
exit status 1
```